services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: hlrms-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: hlrms
      RABBITMQ_DEFAULT_PASS: hlrms_password

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: hlrms-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --save
      - "60"
      - "1000"
      - --requirepass
      - hlrms_redis_password

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REDISCLI_AUTH=hlrms_redis_password redis-cli ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  redis_data: